apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::914002064078:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-177SC2Q2XVEMY
      username: system:node:{{EC2PrivateDNSName}}
    - groups:  
      - system:masters
      rolearn: arn:aws:iam::914002064078:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-07T22:21:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1599"
  uid: 02494358-1bac-4cf1-85c0-9e5a778e12b5
